using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Linq;
using SplineMesh;

public class FixSplineBug : MonoBehaviour
{
    // Start is called before the first frame update
    void Awake()
    {
        var objects = Object.FindObjectsOfType<GameObject>().Where(obj => obj.name == "generated by SplineMeshTiling");
        objects.ToList().ForEach(obj => DestroyImmediate(obj, false));
        var splineMeshes = Object.FindObjectsOfType<SplineMeshTiling>();
        splineMeshes.ToList().ForEach(splineMesh => {
            splineMesh.enabled = false;
            splineMesh.enabled = true;
        });
    }
    // Update is called once per frame
    void Update()
    {
        
    }
}
